const ShopActionTypes = {
  FETCH_COLLECIONS_START: "FETCH_COLLECIONS_START",
  FETCH_COLLECIONS_SUCCESS: "FETCH_COLLECIONS_SUCCESS",
  FETCH_COLLECIONS_FAILURE: "FETCH_COLLECIONS_FAILURE",
};

export default ShopActionTypes;
